-- MySQL Script generated by MySQL Workbench
-- Mon May 29 11:19:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `is_blocked` TINYINT(1) NOT NULL DEFAULT 0,
  `fl_active` VARCHAR(1) NOT NULL DEFAULT 'S',
  `timestamp_c` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp alla creazione',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `isbn` VARCHAR(13) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL,
  `pages` INT UNSIGNED NULL,
  `price` DECIMAL(6,2) UNSIGNED NOT NULL,
  `publication_date` DATE NULL,
  `language` VARCHAR(45) NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp alla creazione',
  `fl_active` VARCHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fl_active` VARCHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fl_active` VARCHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coupon` (
  `code` CHAR(15) NOT NULL,
  `valid` TINYINT(1) NOT NULL DEFAULT 1,
  `discount` INT NOT NULL DEFAULT 0,
  `timestamp_c` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp alla creazione',
  `fl_active` VARCHAR(1) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tot_price` DECIMAL(6,2) GENERATED ALWAYS AS () VIRTUAL,
  `shipping_cost` DECIMAL(6,2) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `coupon_code` CHAR(15) NULL,
  `receiver_name` VARCHAR(45) NOT NULL,
  `add1` VARCHAR(45) NOT NULL,
  `add2` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `cap` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp alla creazione',
  `fl_active` VARCHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (`id`),
  INDEX `fk_Order_User1_idx` (`user_id` ASC),
  INDEX `fk_Order_Coupon1_idx` (`coupon_code` ASC),
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Coupon1`
    FOREIGN KEY (`coupon_code`)
    REFERENCES `mydb`.`Coupon` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_has_Book` (
  `book_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT 1,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`book_id`, `order_id`),
  INDEX `fk_Order_Book1_idx` (`book_id` ASC),
  INDEX `fk_OrderBook_Order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_Order_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderBook_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book_has_Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book_has_Genre` (
  `book_isbn` VARCHAR(13) NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`book_isbn`, `genre_id`),
  INDEX `fk_Book_has_Genre_Genre1_idx` (`genre_id` ASC),
  INDEX `fk_Book_has_Genre_Book1_idx` (`book_isbn` ASC),
  CONSTRAINT `fk_Book_has_Genre_Book1`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `mydb`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_has_Genre_Genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `mydb`.`Genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book_has_Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book_has_Author` (
  `book_isbn` VARCHAR(13) NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`book_isbn`, `author_id`),
  INDEX `fk_Book_has_Author_Author1_idx` (`author_id` ASC),
  INDEX `fk_Book_has_Author_Book1_idx` (`book_isbn` ASC),
  CONSTRAINT `fk_Book_has_Author_Book1`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `mydb`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_has_Author_Author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`Author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wishlist` (
  `user_id` INT NOT NULL,
  `book_isbn` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`user_id`, `book_isbn`),
  INDEX `fk_User_has_Book_Book1_idx` (`book_isbn` ASC),
  INDEX `fk_User_has_Book_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_has_Book_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Book_Book1`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `mydb`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookHistory` (
  `user_id` INT NOT NULL,
  `book_isbn` VARCHAR(13) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `book_isbn`),
  INDEX `fk_User_has_Book_Book2_idx` (`book_isbn` ASC),
  INDEX `fk_User_has_Book_User2_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_has_Book_User2`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Book_Book2`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `mydb`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCart` (
  `user_id` INT NOT NULL,
  `total_price` DECIMAL(6,2) NOT NULL,
  `total_quantity` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_ShoppingCart_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ShoppingCart_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCart_has_Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCart_has_Book` (
  `user_id` INT NOT NULL,
  `book_isbn` VARCHAR(13) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`user_id`, `book_isbn`),
  INDEX `fk_ShoppingCart_has_Book_Book1_idx` (`book_isbn` ASC),
  INDEX `fk_ShoppingCart_has_Book_ShoppingCart1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ShoppingCart_has_Book_ShoppingCart1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`ShoppingCart` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingCart_has_Book_Book1`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `mydb`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vote` (
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `thumb_up` TINYINT(1) NOT NULL,
  `comment` VARCHAR(500) NULL,
  `timestamp_c` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fl_active` VARCHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `fk_User_has_Book_Book3_idx` (`book_id` ASC),
  INDEX `fk_User_has_Book_User3_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_has_Book_User3`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Book_Book3`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
