-- MySQL Script generated by MySQL Workbench
-- Sun May 21 16:50:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userID` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `timestamp_c` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp alla creazione',
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `bookID` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL,
  `pages` SMALLINT(2) UNSIGNED NULL,
  `price` DECIMAL(6,2) UNSIGNED NOT NULL,
  `publication_date` DATE NULL,
  `stock` SMALLINT(2) UNSIGNED NOT NULL DEFAULT 0,
  `ISBN` VARCHAR(13) NULL,
  `language` VARCHAR(45) NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `timestamp_c` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp alla creazione',
  PRIMARY KEY (`bookID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `genreID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genreID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `authorID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`authorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coupon` (
  `Code` CHAR(15) NOT NULL,
  `valid` TINYINT(1) NOT NULL DEFAULT 1,
  `discount` INT NOT NULL DEFAULT 0,
  `timestamp_c` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp alla creazione',
  PRIMARY KEY (`Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `orderID` INT NOT NULL,
  `shipping_cost` VARCHAR(45) NULL,
  `expedition_date` DATE NULL,
  `delivery_date` DATE NULL,
  `tot_price` DECIMAL(6,2) UNSIGNED NOT NULL,
  `state` VARCHAR(45) NULL,
  `Address_addressID` INT NOT NULL,
  `User_userID` INT NOT NULL,
  `timestamp_c` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp alla creazione',
  `Coupon_Code` CHAR(15) NULL,
  `receiver_name` VARCHAR(45) NOT NULL,
  `add1` VARCHAR(45) NOT NULL,
  `add2` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `cap` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_Order_User1_idx` (`User_userID` ASC),
  INDEX `fk_Order_Coupon1_idx` (`Coupon_Code` ASC),
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Coupon1`
    FOREIGN KEY (`Coupon_Code`)
    REFERENCES `mydb`.`Coupon` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_has_Book` (
  `Book_bookID` INT NOT NULL,
  `Order_orderID` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT 1,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`Book_bookID`, `Order_orderID`),
  INDEX `fk_Order_Book1_idx` (`Book_bookID` ASC),
  INDEX `fk_OrderBook_Order1_idx` (`Order_orderID` ASC),
  CONSTRAINT `fk_Order_Book1`
    FOREIGN KEY (`Book_bookID`)
    REFERENCES `mydb`.`Book` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderBook_Order1`
    FOREIGN KEY (`Order_orderID`)
    REFERENCES `mydb`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book_has_Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book_has_Genre` (
  `Book_bookID` INT NOT NULL,
  `Genre_genreID` INT NOT NULL,
  PRIMARY KEY (`Book_bookID`, `Genre_genreID`),
  INDEX `fk_Book_has_Genre_Genre1_idx` (`Genre_genreID` ASC),
  INDEX `fk_Book_has_Genre_Book1_idx` (`Book_bookID` ASC),
  CONSTRAINT `fk_Book_has_Genre_Book1`
    FOREIGN KEY (`Book_bookID`)
    REFERENCES `mydb`.`Book` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_has_Genre_Genre1`
    FOREIGN KEY (`Genre_genreID`)
    REFERENCES `mydb`.`Genre` (`genreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book_has_Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book_has_Author` (
  `Book_bookID` INT NOT NULL,
  `Author_authorID` INT NOT NULL,
  PRIMARY KEY (`Book_bookID`, `Author_authorID`),
  INDEX `fk_Book_has_Author_Author1_idx` (`Author_authorID` ASC),
  INDEX `fk_Book_has_Author_Book1_idx` (`Book_bookID` ASC),
  CONSTRAINT `fk_Book_has_Author_Book1`
    FOREIGN KEY (`Book_bookID`)
    REFERENCES `mydb`.`Book` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_has_Author_Author1`
    FOREIGN KEY (`Author_authorID`)
    REFERENCES `mydb`.`Author` (`authorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wishlist` (
  `User_userID` INT NOT NULL,
  `Book_bookID` INT NOT NULL,
  PRIMARY KEY (`User_userID`, `Book_bookID`),
  INDEX `fk_User_has_Book_Book1_idx` (`Book_bookID` ASC),
  INDEX `fk_User_has_Book_User1_idx` (`User_userID` ASC),
  CONSTRAINT `fk_User_has_Book_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Book_Book1`
    FOREIGN KEY (`Book_bookID`)
    REFERENCES `mydb`.`Book` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookHistory` (
  `User_userID` INT NOT NULL,
  `Book_bookID` INT NOT NULL,
  PRIMARY KEY (`User_userID`, `Book_bookID`),
  INDEX `fk_User_has_Book_Book2_idx` (`Book_bookID` ASC),
  INDEX `fk_User_has_Book_User2_idx` (`User_userID` ASC),
  CONSTRAINT `fk_User_has_Book_User2`
    FOREIGN KEY (`User_userID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Book_Book2`
    FOREIGN KEY (`Book_bookID`)
    REFERENCES `mydb`.`Book` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCart` (
  `User_userID` INT NOT NULL,
  `total_price` DECIMAL(6,2) NOT NULL,
  `total_quantity` INT NOT NULL,
  PRIMARY KEY (`User_userID`),
  INDEX `fk_ShoppingCart_User1_idx` (`User_userID` ASC),
  CONSTRAINT `fk_ShoppingCart_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCart_has_Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCart_has_Book` (
  `ShoppingCart_User_userID` INT NOT NULL,
  `Book_bookID` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`ShoppingCart_User_userID`, `Book_bookID`),
  INDEX `fk_ShoppingCart_has_Book_Book1_idx` (`Book_bookID` ASC),
  INDEX `fk_ShoppingCart_has_Book_ShoppingCart1_idx` (`ShoppingCart_User_userID` ASC),
  CONSTRAINT `fk_ShoppingCart_has_Book_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_User_userID`)
    REFERENCES `mydb`.`ShoppingCart` (`User_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingCart_has_Book_Book1`
    FOREIGN KEY (`Book_bookID`)
    REFERENCES `mydb`.`Book` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vote` (
  `User_userID` INT NOT NULL,
  `Book_bookID` INT NOT NULL,
  `thumb_up` TINYINT(1) NOT NULL,
  `comment` VARCHAR(500) NULL,
  `timestamp_comment` TIMESTAMP NULL,
  PRIMARY KEY (`User_userID`, `Book_bookID`),
  INDEX `fk_User_has_Book_Book3_idx` (`Book_bookID` ASC),
  INDEX `fk_User_has_Book_User3_idx` (`User_userID` ASC),
  CONSTRAINT `fk_User_has_Book_User3`
    FOREIGN KEY (`User_userID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Book_Book3`
    FOREIGN KEY (`Book_bookID`)
    REFERENCES `mydb`.`Book` (`bookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
