INSERT INTO genre VALUES 
("1", "giallo", "S"),
("2", "thriller", "S"),
("3", "horror", "S"),
("4", "fantasy", "S"),
("5", "fantascienza", "S"),
("6", "bambini", "S"),
("7", "ragazzi", "S"),
("8", "societa", "S"),
("9", "politica", "S"),
("10", "storia", "S"),
("11", "economia", "S"),
("12", "diritto", "S"),
("13", "cucina", "S"),
("14", "fumetto", "S");